version: "3.8"
services:
  db:
    image: postgres
    hostname: database
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: shop
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    build:
      dockerfile: /Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=database
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=admin123
      - DATABASE_NAME=shop
      - DATABASE_PORT=5432
    links:
      - db
    depends_on:
      - db
    volumes:
      - backend_uploads:/app/uploads
volumes:
  db_data:
  backend_uploads: